### ISSUE TITLE
Bad name validation

### ISSUE THREAD

**Issue by xbauquet** [Madaragog/P3Game#1]
https://github.com/Madaragog/P3Game/blob/8e378be9b153b2f4e7e0436585abd1a907e8b4f5/P3Game/P3Game/Player/PlayerManager.swift#L28

Here you only check if the name is empty but you should also check that the name has not been used already.

**Comment by Madaragog** [comment]
I solved it with the line 23 to 26 with this :
while player2?.playerName == player1!.playerName {
            print("Sorry but you can't have the same name as the player 1")
            player2 = createPlayer()
        }
