### ISSUE TITLE
Bad place

### ISSUE THREAD

**Issue by xbauquet** [Madaragog/P3Game#2]
https://github.com/Madaragog/P3Game/blob/8e378be9b153b2f4e7e0436585abd1a907e8b4f5/P3Game/P3Game/Fight/Fight.swift#L119

https://github.com/Madaragog/P3Game/blob/8e378be9b153b2f4e7e0436585abd1a907e8b4f5/P3Game/P3Game/Fight/Fight.swift#L120

1 - This actions should be directly in the attack() method in Charaters.
2 - ONLY classes can start with a capital letter

**Comment by Madaragog** [comment]
I solved it in the attack(), and specialAttack method in character with :

func attack(opponent: Character) {
        opponent.lp -= weapon.damage
        opponent.TotalDamageReceived += weapon.damage
        TotalDamageGiven += weapon.damage
    }

func attack(opponent: Character) {
        opponent.lp -= weapon.damage
        opponent.TotalDamageReceived += weapon.damage
        TotalDamageGiven += weapon.damage
    }
