### ISSUE TITLE
Useless use of memory 

### ISSUE THREAD

**Issue by xbauquet** [Madaragog/P3Game#3]
https://github.com/Madaragog/P3Game/blob/8e378be9b153b2f4e7e0436585abd1a907e8b4f5/P3Game/P3Game/Chest/Chest.swift#L20

Here you are instanciating 3 Weapons when you only need one ... this is pretty bad for the phone memory.

**Comment by Madaragog** [comment]
I solved it (the func is too long but I don't know how to do better):

class Chest {
//    the function to add the random weapon
     static func chestRandomWeapon(_ attacker: Character) {
        let randomWeapon = [1, 2, 3, 4, 5][Int(arc4random_uniform(5))]
        let randomNumber = [1, 2, 3][Int(arc4random_uniform(3))]
        
        if randomWeapon == 5 {
            switch attacker {
            case is Fighter:
                switch randomNumber {
                case 1:
                    attacker.weapon = Sword()
                case 2:
                    attacker.weapon = Spear()
                case 3:
                    attacker.weapon = Nunchaku()
                default:
                    fatalError("Unknown type of character")
                }
            case is Wizard:
                switch randomNumber {
                case 1:
                    attacker.weapon = MagicStick()
                case 2:
                    attacker.weapon = MagicWand()
                case 3:
                    attacker.weapon = MagicalGrimoire()
                default:
                    fatalError("Unknown type of character")
                }
            case is Colossus:
                switch randomNumber {
                case 1:
                    attacker.weapon = Mace()
                case 2:
                    attacker.weapon = Warhammer()
                case 3:
                    attacker.weapon = GreatSword()
                default:
                    fatalError("Unknown type of character")
                }
            case is Dwarf:
                switch randomNumber {
                case 1:
                    attacker.weapon = Axe()
                case 2:
                    attacker.weapon = DoubleEdgedAxe()
                case 3:
                    attacker.weapon = Dagger()
                default:
                    fatalError("Unknown type of character")
                }
            default:
                fatalError("Unknown type of character")
            }
        }
    }
}
