### ISSUE TITLE
Name will never change

### ISSUE THREAD

**Issue by xbauquet** [Madaragog/P3Game#4]
https://github.com/Madaragog/P3Game/blob/8e378be9b153b2f4e7e0436585abd1a907e8b4f5/P3Game/P3Game/Character/Character.swift#L25

This could be a let

**Comment by xbauquet** [comment]
https://github.com/Madaragog/P3Game/blob/8e378be9b153b2f4e7e0436585abd1a907e8b4f5/P3Game/P3Game/Character/Character.swift#L29

Same problem here.

**Comment by Madaragog** [comment]
Solved
